/*
Copyright 2026 Ylian Saint-Hilaire
Licensed under the Apache License, Version 2.0 (the "License");
http://www.apache.org/licenses/LICENSE-2.0
*/

import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:htcommander/sarsat/sarsat_1g_decoder.dart';
import 'package:htcommander/sarsat/sarsat_1g_demodulator.dart';
import 'package:htcommander/sarsat/sarsat_monitor.dart';

// Golden frames generated by tools/gen_vectors2.py, whose BCH encoder is
// verified bit-for-bit against the reference decoder's CRC (dec406_v1g.c) and
// its published example frame 8E3301E2402B002BBA863609670908.
//
// Real beacon (country 227, protocol 3 = Standard Location / 24-bit aircraft):
const String _refFrame =
    '111111111111111000101111100011100011001100000001111000100100000000101011000000000010101110111010100001100011011000001001011001110000100100001000';
// Synthetic Standard Location: country 227, protocol 6, position 43.75N 7.25E:
const String _stdLocFrame =
    '111111111111111000101111100011100011011000011110110100011101011100101011110000001110101001111101011111010000000000000000000000000000000000000000';
// Real self-test ELT-DT beacon recovered from Sarsat.wav (country 227):
const String _selfTestFrame =
    '111111111111111011010000100011100011100100000100100011010001010110001010110000000001111000111010101001001000001010000101011010000010010011001110';

List<int> _bits(String s) => s.split('').map(int.parse).toList();

void main() {
  group('Sarsat1gDecoder frame parsing', () {
    test('decodes reference frame with valid BCH', () {
      final f = Sarsat1gDecoder.decode(_bits(_refFrame))!;
      expect(f.length, 144);
      expect(f.crc1Ok, isTrue);
      expect(f.crc2Ok, isTrue);
      expect(f.corrections1, 0);
      expect(f.countryCode, 227);
      expect(f.protocolCode, 3);
      expect(f.protocol, Sarsat1gProtocol.standardLocation);
      expect(f.hexId, '1C6603C480FFBFF');
      expect(f.isTest, isFalse);
    });

    test('decodes synthetic Standard Location with position', () {
      final f = Sarsat1gDecoder.decode(_bits(_stdLocFrame))!;
      expect(f.crc1Ok, isTrue);
      expect(f.crc2Ok, isTrue);
      expect(f.countryCode, 227);
      expect(f.protocolCode, 6);
      expect(f.protocol, Sarsat1gProtocol.standardLocation);
      expect(f.hexId, '1C6C3DA3AEFFBFF');
      expect(f.hasPosition, isTrue);
      expect(f.latitude, closeTo(43.75, 1e-9));
      expect(f.longitude, closeTo(7.25, 1e-9));
    });

    test('rejects wrong-length input', () {
      expect(Sarsat1gDecoder.decode(List<int>.filled(100, 0)), isNull);
    });

    test('decodes a self-test ELT-DT beacon', () {
      final f = Sarsat1gDecoder.decode(_bits(_selfTestFrame))!;
      expect(f.length, 144);
      expect(f.crc1Ok, isTrue);
      expect(f.crc2Ok, isTrue);
      expect(f.isTest, isTrue);
      expect(f.countryCode, 227);
      expect(f.protocolCode, 9);
      expect(f.protocol, Sarsat1gProtocol.emergencyElt);
      expect(f.hexId, '1C72091A2B3FDFF');
    });
  });

  group('Sarsat1gDetails structured record', () {
    test('bitsToHex renders the full frame', () {
      final f = Sarsat1gDecoder.decode(_bits(_selfTestFrame))!;
      final hex = Sarsat1gDecoder.bitsToHex(f.bits);
      expect(hex.length, 36); // 144 bits / 4
      expect(hex, 'FFFED08E39048D158AC01E3AA482856824CE');
    });

    test('fromFrame + JSON round-trip preserves fields', () {
      final f = Sarsat1gDecoder.decode(_bits(_selfTestFrame))!;
      final d = Sarsat1gDetails.fromFrame(f, countryName: 'France');
      final round = Sarsat1gDetails.fromJson(d.toJson());
      expect(round.lengthBits, 144);
      expect(round.crc1Ok, isTrue);
      expect(round.crc2Ok, isTrue);
      expect(round.countryCode, 227);
      expect(round.countryName, 'France');
      expect(round.protocolCode, 9);
      expect(round.hexId, '1C72091A2B3FDFF');
      expect(round.isTest, isTrue);
      expect(round.rawHex, Sarsat1gDecoder.bitsToHex(f.bits));
      expect(round.count, 1);
    });

    test('coalescing metadata (count / last received) round-trips', () {
      final f = Sarsat1gDecoder.decode(_bits(_selfTestFrame))!;
      final last = DateTime.fromMillisecondsSinceEpoch(1734000000000);
      final d = Sarsat1gDetails.fromFrame(
        f,
        countryName: 'France',
        count: 5,
        lastReceivedTime: last,
      );
      final round = Sarsat1gDetails.fromJson(d.toJson());
      expect(round.count, 5);
      expect(round.lastReceivedTime, last);
    });
  });

  group('Sarsat1gDecoder BCH error correction', () {
    for (final nErrors in [1, 2, 3]) {
      test('corrects $nErrors bit error(s) in the protected field', () {
        final original = _bits(_refFrame);
        final corrupted = List<int>.from(original);
        // Flip nErrors distinct bits inside the BCH-1 span (24..105).
        final positions = [30, 55, 90].take(nErrors);
        for (final p in positions) {
          corrupted[p] ^= 1;
        }
        final f = Sarsat1gDecoder.decode(corrupted)!;
        expect(f.crc1Ok, isTrue);
        expect(f.corrections1, nErrors);
        // Recovered payload matches the original beacon.
        expect(f.hexId, '1C6603C480FFBFF');
        expect(f.countryCode, 227);
      });
    }
  });

  group('Sarsat1gDemodulator round-trip', () {
    for (final fs in [32000, 37500, 48000]) {
      test('modulate -> demodulate recovers the frame at ${fs}Hz', () {
        final frame = _bits(_refFrame);
        final pcm = Sarsat1gModulator.modulate(frame, sampleRate: fs);
        final demod = Sarsat1gDemodulator(fs);
        final frames = demod.decode(pcm);
        expect(frames, isNotEmpty);
        final f = frames.first;
        expect(f.crc1Ok, isTrue);
        expect(f.crc2Ok, isTrue);
        expect(f.hexId, '1C6603C480FFBFF');
        expect(f.bits, equals(frame));
      });
    }

    test('recovers Standard Location position through the demodulator', () {
      const fs = 37500;
      final frame = _bits(_stdLocFrame);
      final pcm = Sarsat1gModulator.modulate(frame, sampleRate: fs, carrierHz: 1500);
      final frames = Sarsat1gDemodulator(fs, nominalCarrierHz: 1500).decode(pcm);
      expect(frames, isNotEmpty);
      final f = frames.first;
      expect(f.latitude, closeTo(43.75, 1e-9));
      expect(f.longitude, closeTo(7.25, 1e-9));
    });

    test('decodes under additive noise', () {
      const fs = 37500;
      final frame = _bits(_refFrame);
      final pcm = Sarsat1gModulator.modulate(
        frame,
        sampleRate: fs,
        amplitude: 12000,
        noiseStdDev: 2500, // ~13 dB SNR
        seed: 7,
      );
      final frames = Sarsat1gDemodulator(fs).decode(pcm);
      expect(frames, isNotEmpty);
      expect(frames.first.hexId, '1C6603C480FFBFF');
    });
  });

  group('SarsatMonitor streaming (audio-engine style)', () {
    test('decodes a burst fed in small chunks then flushed', () async {
      const fs = 32000;
      final frame = _bits(_refFrame);
      final pcm = Sarsat1gModulator.modulate(frame, sampleRate: fs);
      final bytes = pcm.buffer.asUint8List();

      final monitor = SarsatMonitor(sampleRate: fs);
      final decoded = <Sarsat1gFrame>[];
      final sub = monitor.onDecoded.listen(decoded.add);

      // Feed 256-byte chunks, mimicking the audio engine's frame cadence.
      const chunk = 256;
      for (int off = 0; off < bytes.length; off += chunk) {
        final len =
            (off + chunk <= bytes.length) ? chunk : bytes.length - off;
        monitor.processPcm16(bytes, off, len);
      }
      monitor.flush();
      await Future<void>.delayed(Duration.zero);

      expect(decoded, isNotEmpty);
      expect(decoded.first.hexId, '1C6603C480FFBFF');
      expect(decoded.first.crc1Ok, isTrue);

      await sub.cancel();
      monitor.dispose();
    });

    test('emits nothing for a too-short / noise-only burst', () async {
      const fs = 32000;
      final monitor = SarsatMonitor(sampleRate: fs);
      final decoded = <Sarsat1gFrame>[];
      final sub = monitor.onDecoded.listen(decoded.add);

      // ~50 ms of noise: below the minimum burst length, must be ignored.
      final noise = Int16List(fs ~/ 20);
      for (int i = 0; i < noise.length; i++) {
        noise[i] = ((i * 31) % 2000) - 1000;
      }
      final bytes = noise.buffer.asUint8List();
      monitor.processPcm16(bytes, 0, bytes.length);
      monitor.flush();
      await Future<void>.delayed(Duration.zero);

      expect(decoded, isEmpty);
      await sub.cancel();
      monitor.dispose();
    });
  });
}
